# Generated by Django 6.0.1 on 2026-01-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('contato', models.CharField(max_length=11)),
                ('observacoes', models.TextField(blank=True)),
                ('criando_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
