# Generated by Django 6.0.1 on 2026-01-29 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_pagamentos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagamentos',
            new_name='Pagamento',
        ),
        migrations.RenameField(
            model_name='pagamento',
            old_name='obsevacoes',
            new_name='observacoes',
        ),
    ]
