# Generated by Django 6.0.1 on 2026-02-02 10:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_pagamentos_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('pagamento_registrado', 'Pagamento registrado'), ('pagamento_confirmado', 'Pagamento confirmado'), ('pagamento_estornado', 'Pagamento estornado'), ('ajuste_manual', 'Ajuste manual')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historicos', to='website.pagamento')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_financeiro', to='website.proposta')),
            ],
            options={
                'verbose_name': 'Histórico Financeiro',
                'verbose_name_plural': 'Históricos Financeiros',
                'ordering': ['criado_em'],
            },
        ),
    ]
