# Generated by Django 6.0.1 on 2026-02-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_historicofinanceiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Não Informado')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='HistoricoFianceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.pagamento')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.proposta')),
            ],
        ),
    ]
