# Generated by Django 6.0.1 on 2026-02-05 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_cliente_sexo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='historicofinanceiro',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Histórico Financeiro', 'verbose_name_plural': 'Históricos Financeiros'},
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='proposta',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Proposta', 'verbose_name_plural': 'Propostas'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='criando_em',
            new_name='criado_em',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contato',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to='website.cliente'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='prestador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('enviada', 'Enviada'), ('visualizada', 'Visualizada'), ('aceita', 'Aceita'), ('cancelada', 'Cancelada'), ('concluida', 'Concluída')], default='rascunho', max_length=20),
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prestador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
            },
        ),
        migrations.CreateModel(
            name='PrestadorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_prestadores', to='website.cliente')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_clientes', to='website.prestador')),
            ],
            options={
                'verbose_name': 'Vínculo Prestador-Cliente',
                'verbose_name_plural': 'Vínculos Prestador-Cliente',
                'ordering': ['-criado_em'],
                'unique_together': {('prestador', 'cliente')},
            },
        ),
        migrations.DeleteModel(
            name='HistoricoFianceiro',
        ),
    ]
